### ISSUE TITLE
App Connection List Don't Show the Icons

### ISSUE THREAD

**Issue by chez14** [automatisch/automatisch#1566]
While opening "Add a new app connection" (My Apps → Add connection), the icon is loaded with the the `BASE_URL` instead of using `WEB_APP_URL`. This causes the icon not loaded in the web app with specific configuration (docker config attached).

Is this expected? My understanding is, since this icon will be displayed on the web app, it probably better to use `WEB_APP_URL` instead of `BASE_URL`.

Thank you!

## Screenshot:

![image](https://github.com/automatisch/automatisch/assets/5555026/bdd18104-8dd9-4b04-93b9-835150ee3e68)

## Docker Config

Configurations:
- `.env` file:
  ```env
  HOST=0.0.0.0
  WEB_APP_URL=http://127.0.0.80:8000/
  WEBHOOK_URL=http://127.0.0.80:8000/
  PROTOCOL=http
  PORT=3000
  ```
- `docker-compose.yml` file:
  ```yml
  version: '3.9'
  
  services:
    main:
      image: ghcr.io/automatisch/automatisch:0.10.0
      ports:
        - '127.0.0.80:8000:3000'
      depends_on:
        redis:
          condition: service_started
      env_file:
        - ./.env
      volumes:
        - ./automatisch_storage:/automatisch/storage
  ```
