### ISSUE TITLE
Webhook not working properly. works on test but not on in live

### ISSUE THREAD

**Issue by igalg99** [automatisch/automatisch#1936]
I have setup and installed Automatisch via Docker on my synology DSM 7.2. I have a stack with both main and worker automatisch installed. I have used . I have used this turotrial for installation: https://mariushosting.com/how-to-install-automatisch-on-your-synology-nas/

I have reversed proxy configured via the DSM log in portal and I can access the automatisch properly via " automatisch.my-domain.synolgy.me " 
I have created a webhook trigger and got an automatically generated URL. however the url has the link like this : https://automatisch.my-domain.synology.me:3000/webhook.... " 

PROBLEM: 
when I test the trigger it works but when I copy the link and put it in my browser to test it , the link doesnt load. I have tried this link in my wordpress website and I get a "webhook error".  

I tried to search for solution and answer but I could not find something relevant to my problem. my working theory is that the problem lies with port "3000" within the gernerated URL which doesnt fit really to my synology reverse proxy settings. I have not links on my domain which has port right after them . the port is already configured in the DSM login portal.  
I dont find a way how I can change the generated link settings and why it gives me a a link with  a port in the end. 

any suggestion what can be done?

**Comment by igalg99** [comment]
update: I have found this in the docker stack. maybe I need to change something here but I have no idea what. 

![image](https://github.com/automatisch/automatisch/assets/86168630/0aa5dbc1-7380-4c7c-92d2-6c85ca7d7aa8)

**Comment by barinali** [comment]
> update: I have found this in the docker stack. maybe I need to change something here but I have no idea what.
> 
> ![image](https://private-user-images.githubusercontent.com/86168630/340241170-0aa5dbc1-7380-4c7c-92d2-6c85ca7d7aa8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2NDM3ODYsIm5iZiI6MTcxODY0MzQ4NiwicGF0aCI6Ii84NjE2ODYzMC8zNDAyNDExNzAtMGFhNWRiYzEtNzM4MC00YzdjLTkyZDItNmM4NWNhN2Q3YWE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDE2NTgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzMTNmYmYwNzgwMDU2M2E4M2FlMzE4NTdiZjQ2OGE1M2NjZDRkODU1YTIzNDE1ZGEzMGQ2YjI4MmU3MGFiMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2tc2WRnSJtz4pik2AceftnV9i6gvatthLdx-cjNKXig)

`WEBHOOK_URL` should have the URL where the API can be accessed. Given that you followed the guide from mariushosting.com, it is likely to be "automatisch.my-domain.synolgy.me" as it serves both the web application and the API.

**Comment by igalg99** [comment]
Yes but the url which is generated is not working for me. It cannot be reached because it has the port 3000 in the url for some reason. I have tried many possible solutions but eventually I gave up and used the alternative "Activepieces" which had a working webhook url for me to use. 
I liked automatisch but I could not get it it work unfortunately :(

**Comment by barinali** [comment]
> Yes but the url which is generated is not working for me.

I'm not sure if we are on the same page. I understand you can access your Automatisch instance on your Synology URL, right? If so, I suggest you use that address in your WEBHOOK_URL environment variable. By the way, you could test this approach without making any changes in your deployment configuration.

Let's say you visit Automatisch at `a.tld` and a flow is at `a.tld/flows/id`, and it gives you a webhook URL like `a.tld:3000/webhooks/flows/id`. You can take the path from the given webhook URL and use it with the host of Automatisch to see if your requests succeed. If so, you can add `WEBHOOK_URL=a.tld` in your environment variable and perform a redeployment. This should provide you with actual working URLs in the flow editor.

**Comment by igalg99** [comment]
I have tried those solution/troubleshooting already without success. Even
tried to adjust firewall and port forwarding settings just in case it is
related to that but still no success.. it is just one of these annoying
problems what probably very specific and the solution is probably very
simple and silly but since I have already found an alternative, I am not
going to chase after resolution at this point.

Regardless, thank you for your help and suggestions!

**Comment by barinali** [comment]
Thanks for your response. I'll close this issue as you have moved forward, and we cannot reproduce this in the direction of the suggestions I provided above. If you ever need further help, I'd be happy to take a closer look at your case.

**Comment by Crandy9** [comment]
@barinali I'm also experiencing this same issue, I setup a Twilio Trigger and a SendGrid SMTP Action connections successfully, but the trigger isn't working when I send an SMS message to my Twilio number. The Trigger isn't triggering. I'm running `docker compose up` in production to see events in real time, but when I send an SMS to my Twilio number, nothing is happening in Automatisch.

**Comment by Crandy9** [comment]
@barinali this is my webhook URL: `/api/v1/flows/<ID>` that is displayed in the console when I published my flow. 

I have my real site name in the env var `WEBHOOK_URL` which I set in my docker-compose.yml file:
```
  main:
    build:
      context: ./docker
      dockerfile: Dockerfile.compose
    entrypoint: /compose-entrypoint.sh
    ports:
      - '${MAIN_HTTP_PORT}:${MAIN_HTTP_PORT}'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - HOST=${HOST}
      - PROTOCOL=${PROTOCOL}
      - PORT=${MAIN_HTTP_PORT}
      - APP_ENV=${APP_ENV}
      - REDIS_HOST=${REDIS_HOST}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - WEBHOOK_SECRET_KEY=${WEBHOOK_SECRET_KEY}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - APP_SECRET_KEY=${APP_SECRET_KEY}
    volumes:
      - automatisch_storage:/automatisch/storage
  worker:
    build:
      context: ./docker
      dockerfile: Dockerfile.compose
    entrypoint: /compose-entrypoint.sh
    depends_on:
      - main
    environment:
      - APP_ENV=${APP_ENV}
      - REDIS_HOST=${REDIS_HOST}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - WEBHOOK_SECRET_KEY=${WEBHOOK_SECRET_KEY}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - APP_SECRET_KEY=${APP_SECRET_KEY}
      - WORKER=true
    volumes:
      - automatisch_storage:/automatisch/storage
```
