### ISSUE TITLE
Improved Dokcer Compose File

### ISSUE THREAD

**Issue by FuckingToasters** [automatisch/automatisch#1960]
I've improved various different things. Note that a slight modification to the `setup/Dockerfile.compose` is required as otherwise, the entrypoint scripts won't have the execute permission and thus the containers wouldn't start. I've tried to make a Pullrequest about this but wasn't able to (Create Buttoin is disabled).

Here the updated Dockerfile.compose:
```
# syntax=docker/dockerfile:1
FROM automatischio/automatisch:latest
WORKDIR /automatisch

RUN apk add --no-cache openssl dos2unix

COPY ./compose-entrypoint.sh /compose-entrypoint.sh
RUN dos2unix /compose-entrypoint.sh

EXPOSE 3000

# Ensure the script has executable permissions
RUN chmod +x /compose-entrypoint.sh

ENTRYPOINT ["sh", "/compose-entrypoint.sh"]
```

Before using this compose file, make sure all folders exist:
```sh
mkdir -p /docker/automatisch/setup
mkdir -p /docker/automatisch/redis_data
mkdir -p /docker/automatisch/pg_data
mkdir -p /docker/automatisch/storage
```

Grab the updated compose file (I have more services but removed services unrelated to automatisch before poasting it in):
```yml
version: '3.0'

services:
  postgres-automatisch:
    container_name: postgres-automatisch
    image: 'postgres:14.5'
    restart: unless-stopped
    networks:
      - revproxy
    env_file:
      - "./automatisch.env"
    volumes:
      - automatisch_pg_data:/var/lib/postgresql/data

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5

  redis-automatisch:
    container_name: redis-automatisch
    image: 'redis:7.0.4'
    restart: unless-stopped
    volumes:
    - redis_automatisch_data:/data
    networks:
      - revproxy

  automatisch-main:
    container_name: automatisch-main
    build:
      context: /docker/automatisch/setup
      dockerfile: Dockerfile.compose
    entrypoint: /compose-entrypoint.sh
    restart: unless-stopped
    #ports:
      #- '3000:3000'
    networks:
      - revproxy
    depends_on:
      postgres-automatisch:
        condition: service_healthy
      redis-automatisch:
        condition: service_started
    env_file:
      - "./automatisch.env"
    volumes:
      - automatisch_storage:/automatisch/storage

  automatisch-worker:
    container_name: automatisch-worker
    build:
      context: /docker/automatisch/setup
      dockerfile: Dockerfile.compose
    entrypoint: /compose-entrypoint.sh
    depends_on:
      - automatisch-main
    env_file:
      - "./automatisch.env"
    volumes:
      - automatisch_storage:/automatisch/storage

volumes:
  # postgres volumes
  automatisch_pg_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /docker/automatisch/pg_data

  # redis volumes
  redis_automatisch_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /docker/automatisch/redis_data

  # service volumes
  automatisch_storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /docker/automatisch/storage

networks:
  revproxy:
    external: true
```

automatisch.env file:
```
# automatisch-postgres
POSTGRES_HOST=postgres-automatisch
POSTGRES_DATABASE=automatisch
POSTGRES_USERNAME=postgres

POSTGRES_DB=automatisch
POSTGRES_USER=postgres
POSTGRES_PASSWORD=HyucGgDYjH3kMVLdHzsffMzZ7atcsWMbn

# automatisch-redis
REDIS_HOST=redis-automatisch

# automatisch-main & automatisch-worker
HOST=localhost
PROTOCOL=http
PORT=3000
APP_ENV=production
ENCRYPTION_KEY
WEBHOOK_SECRET_KEY
APP_SECRET_KEY
WORKER=true
```

These modifications ensure clean volume mounting, not exposing any ports and running the containers in the revproxy docker network so that you can  use nginx proxy manager to bind the services to a cloudflare protected domain. Users won't be abl to lookup the real vps ip at https://search.censys.io when using docker networks with nginx proxy manager.

**Comment by Karlostavitch1** [comment]
Thank you. I also experienced the same issue on first time install.

**Comment by stanthewizzard** [comment]
for redis you can add
```

    healthcheck:
      test: ["CMD", "redis-cli", "-X", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
```
