### ISSUE TITLE
Twilio Trigger and SendGrid Action Not Working

### ISSUE THREAD

**Issue by Crandy9** [automatisch/automatisch#2340]
I have a Twilio Trigger with a "Receive SMS" event setup, and I have a subsequent SMTP Action twitha "Send an email" event to forward SMS messages sent to my Twilio number to my email. Both Twilio and SendGrid Trigger and Action were tested successfully. I published the flow, but when I send a test SMS to my Twilio number, nothing's happening. Automatisch should be intercepting the SMS message to the Twilio number and emailing it to me via SendGrid Action. I'm deployed to a remote server running the docker compose app, and using nginx to provide an SSL cert over https. I'm not seeing any errors in my network or system.

**Comment by Crandy9** [comment]
Here are my docker-compose.yml:
```
version: '3.9'
networks:
  proxy:
    driver: bridge   
  default:
    name: automatisch_network
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:db8:2::/64
services:
  nginx:
    image: nginx:latest
    depends_on:
      - main      
    restart: unless-stopped
    volumes:
      - ./https/nginx/automatisch_letsencrypt_nginx.conf:/etc/nginx/conf.d/automatisch_letsencrypt_nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - '80:80'
      - '443:443'
  certbot:
     image: certbot/certbot:latest
     volumes:
       - ./certbot/conf:/etc/letsencrypt
       - ./certbot/www:/var/www/certbot     
     command: certonly --webroot -w /var/www/certbot --keep-until-expiring --email ${SSL_CERT_EMAIL} -d ${HOST} --agree-tos
     depends_on:
       - nginx     
  main:
    build:
      context: ./docker
      dockerfile: Dockerfile.compose
    entrypoint: /compose-entrypoint.sh
    ports:
      - '7557:7557'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - HOST=${HOST}
      - PROTOCOL=http
      - PORT=7557
      - APP_ENV=production
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_DATABASE=automatisch
      - POSTGRES_USERNAME=automatisch_user
      - POSTGRES_PASSWORD=automatisch_password
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - WEBHOOK_SECRET_KEY=${WEBHOOK_SECRET_KEY}
      - APP_SECRET_KEY=${APP_SECRET_KEY}
    volumes:
      - automatisch_storage:/automatisch/storage
  worker:
    build:
      context: ./docker
      dockerfile: Dockerfile.compose
    entrypoint: /compose-entrypoint.sh
    depends_on:
      - main
    environment:
      - APP_ENV=production
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_DATABASE=automatisch
      - POSTGRES_USERNAME=automatisch_user
      - POSTGRES_PASSWORD=automatisch_password
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - WEBHOOK_SECRET_KEY=${WEBHOOK_SECRET_KEY}
      - APP_SECRET_KEY=${APP_SECRET_KEY}
      - WORKER=true
    volumes:
      - automatisch_storage:/automatisch/storage
  postgres:
    image: 'postgres:14.5'
    environment:
      - POSTGRES_DB=automatisch
      - POSTGRES_USER=automatisch_user
      - POSTGRES_PASSWORD=automatisch_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: 'redis:7.0.4'
    volumes:
      - redis_data:/data
volumes:
  automatisch_storage:
  postgres_data:
  redis_data:

```
