### ISSUE TITLE
WEB_APP_URL not respected by connection additions

### ISSUE THREAD

**Issue by DeaeLunae** [automatisch/automatisch#802]
The WEB_APP_URL environmental variable is not used to create the OAuth Redirect URL.

This isn't an issue in a lot of cases, but it does cause connections to fail if you're doing something like hosting over nginx with proxy_pass.

Current workaround:

docker-compose.yml:
```
services:
  main:
[...]
    ports:
      - '3000:443'
[...]
    environment:
      - HOST=auto.[redacted].com
      - PROTOCOL=https
      - PORT=443
```

nginx site conf:
```
upstream automatisch {
        server 127.0.0.1:3000;
        keepalive 16;
}

server {
[...]
        location / {
                [...]
                proxy_pass https://automatisch;  # HTTPS on proxy_pass undesirable
        }
```
